=== api-evangelist/microsoft-planner/json-schema/microsoft-planner-planner-task-update-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "PlannerTaskUpdate",
  "type": "object",
  "description": "Request body for updating a task",
  "properties": {
    "title": {
      "type": "string"
    },
    "bucketId": {
      "type": "string"
    },
    "priority": {
      "type": "integer"
    },
    "percentComplete": {
      "type": "integer"
    },
    "startDateTime": {
      "type": "string"
    },
    "dueDateTime": {
      "type": "string"
    },
    "conversationThreadId": {
      "type": "string"
    },
    "orderHint": {
      "type": "string"
    },
    "assigneePriority": {
      "type": "string"
    },
    "previewType": {
      "type": "string"
    }
  }
}

=== api-evangelist/microsoft-planner/examples/microsoft-planner-planner-task-update-example.json
{
  "title": "Example Title",
  "bucketId": "500123",
  "priority": 10,
  "percentComplete": 10,
  "startDateTime": "example_value",
  "dueDateTime": "example_value",
  "conversationThreadId": "500123",
  "orderHint": "example_value",
  "assigneePriority": "example_value",
  "previewType": "example_value"
}
